/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/leaderboards": {
    /** Get a list of leaderboards based on filters */
    get: {
      /** Get a list of leaderboards based on filters */
      parameters?: {
          /** @description Filter by verified (⚠️️deprecation notice) */
          /** @description Filter by ranked */
          /** @description Filter by qualified */
          /** @description Filter by loved */
          /** @description Filter by minimum star value */
          /** @description Filter by maxiumum star value */
          /** @description Which category to sort by (0 = trending, date ranked = 1, scores set = 2, star difficulty = 3, author = 4) */
          /** @description Which direction to sort (0 = descending, 1 = ascending) */
          /** @description Only return one leaderboard of each id */
          /** @description (default true) */
        query?: {
          search?: string;
          verified?: boolean;
          ranked?: boolean;
          qualified?: boolean;
          loved?: boolean;
          minStar?: number;
          maxStar?: number;
          category?: number;
          sort?: number;
          unique?: boolean;
          page?: number;
          withMetadata?: boolean;
        };
      };
      responses: {
        /** @description A list of leaderboards */
        200: {
          content: {
            "application/json": components["schemas"]["LeaderboardInfoCollection"];
          };
        };
        /** @description Invalid parameter */
        422: never;
      };
    };
  };
  "/api/leaderboard/by-id/{leaderboardId}/info": {
    /** Gets leaderboard information by ScoreSaber leaderboardId */
    get: {
      /** Gets leaderboard information by ScoreSaber leaderboardId */
      parameters: {
          /** @description ScoreSaber leaderboardId */
        path: {
          leaderboardId: number;
        };
      };
      responses: {
        /** @description Leaderboard information */
        200: {
          content: {
            "application/json": components["schemas"]["LeaderboardInfo"];
          };
        };
        /** @description Not found */
        404: never;
      };
    };
  };
  "/api/leaderboard/by-hash/{hash}/info": {
    /** Gets leaderboard information by map hash */
    get: {
      /** Gets leaderboard information by map hash */
      parameters: {
          /** @description (1 = Easy, 3 = Normal, 5 = Hard, 7 = Expert, 9 = Expert+) */
          /** @description (e.g SoloStandard) */
        query: {
          difficulty: number;
          gameMode?: string;
        };
          /** @description Map hash */
        path: {
          hash: string;
        };
      };
      responses: {
        /** @description Leaderboard information */
        200: {
          content: {
            "application/json": components["schemas"]["LeaderboardInfo"];
          };
        };
        /** @description Not found */
        404: never;
      };
    };
  };
  "/api/leaderboard/by-id/{leaderboardId}/scores": {
    /** Gets leaderboard scores by ScoreSaber leaderboardId */
    get: {
      /** Gets leaderboard scores by ScoreSaber leaderboardId */
      parameters: {
          /** @description Filter by ISO 3166-1 alpha-2 code (comma delimitered) */
          /** @description (default true) */
        query?: {
          countries?: string;
          search?: string;
          page?: number;
          withMetadata?: boolean;
        };
          /** @description ScoreSaber leaderboardId */
        path: {
          leaderboardId: number;
        };
      };
      responses: {
        /** @description A colleciton of Score */
        200: {
          content: {
            "application/json": (components["schemas"]["ScoreCollection"])[];
          };
        };
        /** @description Not found */
        404: never;
      };
    };
  };
  "/api/leaderboard/by-hash/{hash}/scores": {
    /** Gets leaderboard scores by map hash */
    get: {
      /** Gets leaderboard scores by map hash */
      parameters: {
          /** @description (1 = Easy, 3 = Normal, 5 = Hard, 7 = Expert, 9 = Expert+) */
          /** @description Filter by ISO 3166-1 alpha-2 code (comma delimitered) */
          /** @description (e.g SoloStandard) */
          /** @description (default true) */
        query: {
          difficulty: number;
          countries?: string;
          search?: string;
          page?: number;
          gameMode?: string;
          withMetadata?: boolean;
        };
          /** @description Map hash */
        path: {
          hash: string;
        };
      };
      responses: {
        /** @description A collection of Score */
        200: {
          content: {
            "application/json": (components["schemas"]["ScoreCollection"])[];
          };
        };
        /** @description Not found */
        404: never;
      };
    };
  };
  "/api/leaderboard/get-difficulties/{hash}": {
    /** Gets a leaderboards difficulties by hash */
    get: {
      /** Gets a leaderboards difficulties by hash */
      parameters: {
          /** @description Map hash */
        path: {
          hash: string;
        };
      };
      responses: {
        /** @description An Array of Difficulty */
        200: {
          content: {
            "application/json": (components["schemas"]["Difficulty"])[];
          };
        };
        /** @description Not found */
        404: never;
      };
    };
  };
  "/api/players": {
    /** Get a list of players based on filters */
    get: {
      /** Get a list of players based on filters */
      parameters?: {
          /** @description Filter by ISO 3166-1 alpha-2 code (comma delimitered) */
          /** @description (default true) */
        query?: {
          search?: string;
          page?: number;
          countries?: string;
          withMetadata?: boolean;
        };
      };
      responses: {
        /** @description A collection of Player */
        200: {
          content: {
            "application/json": (components["schemas"]["PlayerCollection"])[];
          };
        };
        /** @description Not found */
        404: never;
      };
    };
  };
  "/api/players/count": {
    /** Get a list of active players based on filters */
    get: {
      /** Get a list of active players based on filters */
      parameters?: {
          /** @description Filter by ISO 3166-1 alpha-2 code (comma delimitered) */
        query?: {
          search?: string;
          countries?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "text/plain": number;
          };
        };
        /** @description Not found */
        404: never;
      };
    };
  };
  "/api/player/{playerId}/basic": {
    /** Gets a players basic information */
    get: {
      /** Gets a players basic information */
      parameters: {
        path: {
          playerId: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": (components["schemas"]["Player"])[];
          };
        };
        /** @description Not found */
        404: never;
      };
    };
  };
  "/api/player/{playerId}/full": {
    /** Gets all the players information */
    get: {
      /** Gets all the players information */
      parameters: {
        path: {
          playerId: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": (components["schemas"]["Player"])[];
          };
        };
        /** @description Not found */
        404: never;
      };
    };
  };
  "/api/player/{playerId}/scores": {
    /** Gets scores by playerId */
    get: {
      /** Gets scores by playerId */
      parameters: {
          /** @description The amount of scores to return */
          /** @description Page */
          /** @description (default true) */
        query?: {
          limit?: number;
          sort?: "top" | "recent";
          page?: number;
          withMetadata?: boolean;
        };
        path: {
          playerId: string;
        };
      };
      responses: {
        /** @description A collection of PlayerScore */
        200: {
          content: {
            "application/json": (components["schemas"]["PlayerScoreCollection"])[];
          };
        };
        /** @description Not found */
        404: never;
      };
    };
  };
  "/api/user/{playerId}/refresh": {
    /** Get logged in user information */
    get: {
      /** Get logged in user information */
      parameters: {
        path: {
          playerId: number;
        };
      };
      responses: {
        /** @description OK */
        200: never;
      };
    };
  };
  "/api/user/@me": {
    /** Get logged in user information */
    get: {
      /** Get logged in user information */
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": (components["schemas"]["UserData"])[];
          };
        };
        /** @description Not logged in */
        401: never;
      };
    };
  };
  "/api/user/quest-key": {
    /** Generates a new quest key if one doesn't exist */
    get: {
      /** Generates a new quest key if one doesn't exist */
      responses: {
        /** @description The quest key */
        200: {
          content: {
            "text/plain": string;
          };
        };
        /** @description Not logged in */
        401: never;
      };
    };
  };
  "/api/ranking/requests/top": {
    /** Gets the top 6 rank requests -⚠️deprecation notice */
    get: {
      /** Gets the top 6 rank requests -⚠️deprecation notice */
      responses: {
        /** @description An Array of RankRequestListing */
        200: {
          content: {
            "application/json": (components["schemas"]["RankRequestListing"])[];
          };
        };
      };
    };
  };
  "/api/ranking/requests/belowTop": {
    /** Gets the rest of the ranking requests - ⚠️deprecation notice */
    get: {
      /** Gets the rest of the ranking requests - ⚠️deprecation notice */
      responses: {
        /** @description An Array of RankRequestListing */
        200: {
          content: {
            "application/json": (components["schemas"]["RankRequestListing"])[];
          };
        };
      };
    };
  };
  "/api/ranking/request/{requestId}": {
    /** Gets rank request information by requestId */
    get: {
      /** Gets rank request information by requestId */
      parameters: {
        path: {
          requestId: number;
        };
      };
      responses: {
        /** @description Rank request information */
        200: {
          content: {
            "application/json": components["schemas"]["RankRequestInformation"];
          };
        };
        /** @description Not found */
        404: never;
      };
    };
  };
  "/api/ranking/request/by-id/{leaderboardId}": {
    /** Gets rank request information by ScoreSaber leaderboardId */
    get: {
      /** Gets rank request information by ScoreSaber leaderboardId */
      parameters: {
          /** @description ScoreSaber leaderboardId */
        path: {
          leaderboardId: number;
        };
      };
      responses: {
        /** @description Rank request information */
        200: {
          content: {
            "application/json": components["schemas"]["RankRequestInformation"];
          };
        };
        /** @description Not found */
        404: never;
      };
    };
  };
  "/api/ranking/request/action/rt/create": {
    /** Creates a rank request */
    post: {
      /** Creates a rank request */
      requestBody: {
        content: {
          "application/x-www-form-urlencoded": components["schemas"]["rt_create_body"];
        };
      };
      responses: {
        /** @description The created requestId */
        200: {
          content: {
            "text/plain": number;
          };
        };
        /** @description You don't have permission to view this! */
        403: never;
      };
    };
  };
  "/api/ranking/request/action/rt/vote": {
    /** Votes on a given rank request */
    post: {
      /** Votes on a given rank request */
      requestBody: {
        content: {
          "application/x-www-form-urlencoded": components["schemas"]["rt_vote_body"];
        };
      };
      responses: {
        /** @description OK */
        200: never;
        /** @description You don't have permission to view this! */
        403: never;
      };
    };
  };
  "/api/ranking/request/action/rt/comment": {
    /** Comments on a given rank request */
    post: {
      /** Comments on a given rank request */
      requestBody: {
        content: {
          "application/x-www-form-urlencoded": components["schemas"]["rt_comment_body"];
        };
      };
      responses: {
        /** @description OK */
        200: never;
        /** @description You don't have permission to view this! */
        403: never;
      };
    };
  };
  "/api/ranking/request/action/qat/vote": {
    /** Votes on a given rank request */
    post: {
      /** Votes on a given rank request */
      requestBody: {
        content: {
          "application/x-www-form-urlencoded": components["schemas"]["qat_vote_body"];
        };
      };
      responses: {
        /** @description OK */
        200: never;
        /** @description You don't have permission to view this! */
        403: never;
      };
    };
  };
  "/api/ranking/request/action/qat/comment": {
    /** Comments on a given rank request */
    post: {
      /** Comments on a given rank request */
      requestBody: {
        content: {
          "application/x-www-form-urlencoded": components["schemas"]["qat_comment_body"];
        };
      };
      responses: {
        /** @description OK */
        200: never;
        /** @description You don't have permission to view this! */
        403: never;
      };
    };
  };
  "/api/ranking/request/action/nat/replace": {
    /** Replaces a rank requests leaderboardId */
    post: {
      /** Replaces a rank requests leaderboardId */
      requestBody: {
        content: {
          "application/x-www-form-urlencoded": components["schemas"]["nat_replace_body"];
        };
      };
      responses: {
        /** @description OK */
        200: never;
        /** @description You don't have permission to view this! */
        403: never;
      };
    };
  };
  "/api/ranking/request/action/nat/qualify": {
    /** Qualifies a rank request */
    post: {
      /** Qualifies a rank request */
      requestBody: {
        content: {
          "application/x-www-form-urlencoded": components["schemas"]["nat_qualify_body"];
        };
      };
      responses: {
        /** @description OK */
        200: never;
        /** @description You don't have permission to view this! */
        403: never;
      };
    };
  };
  "/api/ranking/request/action/nat/deny": {
    /** Denies a rank request */
    post: {
      /** Denies a rank request */
      requestBody: {
        content: {
          "application/x-www-form-urlencoded": components["schemas"]["nat_deny_body"];
        };
      };
      responses: {
        /** @description OK */
        200: never;
        /** @description You don't have permission to view this! */
        403: never;
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Metadata: {
      total: number;
      page: number;
      itemsPerPage: number;
    };
    LeaderboardInfo: {
      id: number;
      songHash: string;
      songName: string;
      songSubName: string;
      songAuthorName: string;
      levelAuthorName: string;
      difficulty: components["schemas"]["Difficulty"];
      maxScore: number;
      /** Format: date-time */
      createdDate: string;
      rankedDate: string | (Record<string, unknown> | null);
      qualifiedDate: string | (Record<string, unknown> | null);
      lovedDate: string | (Record<string, unknown> | null);
      ranked: boolean;
      qualified: boolean;
      loved: boolean;
      maxPP: number;
      stars: number;
      positiveModifiers: boolean;
      plays: number;
      dailyPlays: number;
      coverImage: string;
      playerScore: components["schemas"]["Score"] | (Record<string, unknown> | null);
      difficulties: (components["schemas"]["Difficulty"])[];
    };
    LeaderboardInfoCollection: {
      leaderboards: (components["schemas"]["LeaderboardInfo"])[];
      metadata: components["schemas"]["Metadata"];
    };
    LeaderboardPlayer: {
      id: string;
      name: string;
      profilePicture: string;
      country: string;
      permissions: number;
      role: string;
    };
    Difficulty: {
      leaderboardId: number;
      difficulty: number;
      gameMode: string;
      difficultyRaw: string;
    };
    ScoreCollection: {
      scores: (components["schemas"]["Score"])[];
      metadata: components["schemas"]["Metadata"];
    };
    Score: {
      id: number;
      leaderboardPlayerInfo?: components["schemas"]["LeaderboardPlayer"];
      rank: number;
      baseScore: number;
      modifiedScore: number;
      pp: number;
      weight: number;
      modifiers: string;
      multiplier: number;
      badCuts: number;
      missedNotes: number;
      maxCombo: number;
      fullCombo: boolean;
      hmd: number;
      hasReplay: boolean;
      /** Format: date-time */
      timeSet: string;
    };
    PlayerCollection: {
      players: (components["schemas"]["Player"])[];
      metadata: components["schemas"]["Metadata"];
    };
    Player: {
      id: string;
      name: string;
      profilePicture: string;
      country: string;
      pp: number;
      rank: number;
      countryRank: number;
      role: string;
      badges: (components["schemas"]["Badge"])[] | (Record<string, unknown> | null);
      histories: string;
      scoreStats: components["schemas"]["ScoreStats"] | (Record<string, unknown> | null);
      permissions: number;
      banned: boolean;
      inactive: boolean;
    };
    ScoreStats: {
      totalScore: number;
      totalRankedScore: number;
      averageRankedAccuracy: number;
      totalPlayCount: number;
      rankedPlayCount: number;
      replaysWatched: number;
    };
    Badge: {
      description: string;
      image: string;
    };
    PlayerScoreCollection: {
      playerScores: (components["schemas"]["PlayerScore"])[];
      metadata: components["schemas"]["Metadata"];
    };
    PlayerScore: {
      score: components["schemas"]["Score"];
      leaderboard: components["schemas"]["LeaderboardInfo"];
    };
    VoteGroup: {
      upvotes: number;
      downvotes: number;
      myVote: boolean;
      neutral?: number;
    };
    RankRequestListing: {
      requestId: number;
      weight: number;
      leaderboardInfo: components["schemas"]["LeaderboardInfo"];
      created_at: string;
      totalRankVotes: components["schemas"]["VoteGroup"];
      totalQATVotes: components["schemas"]["VoteGroup"];
      difficultyCount: number;
    };
    RankRequestInformation: {
      requestId: number;
      requestDescription: string;
      leaderboardInfo: components["schemas"]["LeaderboardInfo"];
      created_at: string;
      rankVotes: components["schemas"]["VoteGroup"];
      qatVotes: components["schemas"]["VoteGroup"];
      rankComments: (components["schemas"]["Comment"])[];
      qatComments: (components["schemas"]["Comment"])[];
      requestType: number;
      approved: number;
      difficulties: (components["schemas"]["RankingDifficulty"])[];
    };
    RankingDifficulty: {
      requestId: number;
      difficulty: number;
    };
    Comment: {
      username: string;
      userId: string;
      comment: string;
      timeStamp: string;
    };
    UserData: {
      playerId: string;
      permissions: number;
      questKey: string;
    };
    rt_create_body: {
      leaderboardId: string;
      /** @description (0 = unrank, 1 rank) */
      requestType: number;
      description: string;
    };
    rt_vote_body: {
      requestId: string;
      /** @description (0 = down, 1 up) */
      vote: number;
    };
    rt_comment_body: {
      requestId: string;
      comment?: string;
    };
    qat_vote_body: {
      requestId: string;
      /** @description (0 = down, 1 up, 2 = neutral) */
      vote: number;
    };
    qat_comment_body: {
      requestId: string;
      comment?: string;
    };
    nat_replace_body: {
      /** @description The requestId affected */
      requestId: number;
      /** @description The leaderboardId to replace the current requests leaderboardId */
      leaderboardId: number;
      /** @description An updated description */
      description: string;
    };
    nat_qualify_body: {
      requestId: number;
    };
    nat_deny_body: {
      requestId: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export type operations = Record<string, never>;
